### ISSUE TITLE
装环境报错

### ISSUE THREAD

**Issue by lgy2830** [RapidAI/PaddleOCRModelConverter#3]
pip install -r requirements.txt -i https://pypi.douban.com/simple/
Looking in indexes: https://pypi.douban.com/simple/, https://pypi.ngc.nvidia.com
Collecting scipy==1.3.1
  Downloading https://pypi.doubanio.com/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.6/23.6 MB 38.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      <string>:386: UserWarning: Unrecognized setuptools command ('dist_info --output-dir /tmp/pip-modern-metadata-un2r8ngg --keep-egg-info'), proceeding with generating Cython sources and expanding templates
      Traceback (most recent call last):
        File "/home/lgy/anaconda3/envs/ocr-onnx/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/lgy/anaconda3/envs/ocr-onnx/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/lgy/anaconda3/envs/ocr-onnx/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-kmah4yai/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-kmah4yai/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-kmah4yai/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 505, in <module>
        File "<string>", line 481, in setup_package
        File "/tmp/pip-build-env-kmah4yai/overlay/lib/python3.8/site-packages/numpy/distutils/__init__.py", line 8, in <module>
          from . import ccompiler
        File "/tmp/pip-build-env-kmah4yai/overlay/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 17, in <module>
          from numpy.distutils import log
        File "/tmp/pip-build-env-kmah4yai/overlay/lib/python3.8/site-packages/numpy/distutils/log.py", line 6, in <module>
          from distutils.log import Log as old_Log
      ImportError: cannot import name 'Log' from 'distutils.log' (/tmp/pip-build-env-kmah4yai/overlay/lib/python3.8/site-packages/setuptools/_distutils/log.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

你好，装环境报错，不知道为什么？

**Comment by SWHL** [comment]
所在环境的Python版本是多少呢？
