### ISSUE TITLE
本地模型转换报错（no attribute 'txt_url'）

### ISSUE THREAD

**Issue by peterlinux2010** [RapidAI/PaddleOCRModelConverter#5]
升级到最新的0.0.9版本，按照命令参数转换模型直接报以下错，是我的本地环境出问题了么？
paddleocr_convert (0.0.9)
Available versions: 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
  INSTALLED: 0.0.9
  LATEST:    0.0.9

paddleocr_convert -p models/ch_PP-OCRv3_det_infer.tar -o models
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddlepaddle241_gpu\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\paddlepaddle241_gpu\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\paddlepaddle241_gpu\Scripts\paddleocr_convert.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\envs\paddlepaddle241_gpu\lib\site-packages\paddleocr_convert\main.py", line 172, in main
    converter(args.model_path, args.save_dir, args.txt_url)
AttributeError: 'Namespace' object has no attribute 'txt_url'

**Comment by SWHL** [comment]
这个问题昨天刚刚修复，请用v0.0.10版本

**Comment by SWHL** [comment]
issue先关闭了，后续有问题再开
