### ISSUE TITLE
转换ch_PP-OCRv3_rec_slim量化版超轻量模型报错

### ISSUE THREAD

**Issue by peterlinux2010** [RapidAI/PaddleOCRModelConverter#6]
你好，请问当前工具是否支持转换slim量化版超轻量模型？
我在使用最新版本0.0.14的paddleocr_convert，转换ch_PP-OCRv3_rec_slim量化版超轻量模型报错如下：

> paddleocr_convert -p models/ch_PP-OCRv3_rec_slim_infer.tar -o models -txt_path models/ppocr_keys_v1.txt

[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: models\ch_PP-OCRv3_rec_slim_infer\inference.pdmodel
[Paddle2ONNX] Paramters file path: models\ch_PP-OCRv3_rec_slim_infer\inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [Info] The Paddle model is a quantized model.
[Paddle2ONNX] Oops, there are some operators not supported yet, including fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddlepaddle241_gpu\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\paddlepaddle241_gpu\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\paddlepaddle241_gpu\Scripts\paddleocr_convert.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\envs\paddlepaddle241_gpu\lib\site-packages\paddleocr_convert\main.py", line 164, in main
    converter(args.model_path, args.save_dir, args.txt_path)
  File "D:\anaconda3\envs\paddlepaddle241_gpu\lib\site-packages\paddleocr_convert\main.py", line 38, in __call__
    raise ConvertError('paddle2onnx convert failed!')
paddleocr_convert.main.ConvertError: paddle2onnx convert failed!

**Comment by SWHL** [comment]
不支持slim的哈，有算子不支持

**Comment by SWHL** [comment]
issue先关了，有问题再开哈
